light:
  - platform: monochromatic
    output: backlight_pwm
    name: Display
    id: display_backlight
    entity_category: config
    restore_mode: RESTORE_AND_ON
    default_transition_length: 200ms
    initial_state:
      brightness: "50%"
    on_state:
      if:
        condition:
          lambda: |-
            return !id(user_is_interacting);
        then:
          - delay: 220ms # Waiting for transition to be done so the new state is reflected. Maybe there is a better way?
          - lvgl.slider.update:
              id: lvgl_indicator_lcd_brightness_slider
              value: !lambda 'return id(display_backlight).current_values.get_brightness() * 100.0;'
